default:
  jetbrains_plugins_site: "https://plugins.jetbrains.com/"
  repo_url: "https://mysite.com/jetbrains/plugins/"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
  work_dir: ""

proxy:
  enable: False
  address: ""